import { OrderVO } from '@/api/mall/trade/order'

export const testData: OrderVO = [
  {
    id: 2,
    no: '20230817002',
    createTime: new Date('2023-08-17T11:30:00'),
    type: 2,
    terminal: 10,
    userId: 1002,
    userIp: '192.168.1.2',
    userRemark: 'Urgent delivery required',
    status: 20,
    productCount: 2,
    finishTime: null,
    cancelTime: null,
    cancelType: null,
    remark: '',
    payOrderId: 10002,
    payed: false,
    payTime: null,
    payChannelCode: 'wx_app',
    originalPrice: 80,
    orderPrice: 80,
    discountPrice: 0,
    deliveryPrice: 5,
    adjustPrice: 0,
    payPrice: 85,
    deliveryTemplateId: 2002,
    logisticsId: null,
    logisticsNo: '',
    deliveryStatus: 0,
    deliveryTime: null,
    receiveTime: null,
    receiverName: 'Jane Smith',
    receiverMobile: '987-654-3210',
    receiverAreaId: 4002,
    receiverPostCode: 54321,
    receiverDetailAddress: '456 Elm St, Apt 2C',
    afterSaleStatus: 0,
    refundPrice: 0,
    couponId: null,
    couponPrice: 0,
    pointPrice: 0,
    receiverAreaName: 'Townsville',
    items: [
      {
        id: 103,
        userId: 1002,
        orderId: 2,
        spuId: 5003,
        spuName: 'Widget C',
        skuId: 6003,
        picUrl: 'https://example.com/images/widget_c.jpg',
        count: 1,
        originalPrice: 40,
        originalUnitPrice: 40,
        discountPrice: 0,
        payPrice: 40,
        orderPartPrice: 40,
        orderDividePrice: 40,
        afterSaleStatus: 0,
        properties: [
          { propertyId: 7001, propertyName: 'Color', valueId: 8004, valueName: 'Green' },
          { propertyId: 7002, propertyName: 'Size', valueId: 8002, valueName: 'Medium' }
        ]
      },
      {
        id: 104,
        userId: 1002,
        orderId: 2,
        spuId: 5004,
        spuName: 'Widget D',
        skuId: 6004,
        picUrl: 'https://example.com/images/widget_d.jpg',
        count: 1,
        originalPrice: 40,
        originalUnitPrice: 40,
        discountPrice: 0,
        payPrice: 40,
        orderPartPrice: 40,
        orderDividePrice: 40,
        afterSaleStatus: 0,
        properties: [
          { propertyId: 7003, propertyName: 'Color', valueId: 8005, valueName: 'Yellow' },
          { propertyId: 7002, propertyName: 'Size', valueId: 8002, valueName: 'Medium' }
        ]
      }
    ],
    user: {
      id: 1002,
      nickname: 'janesmith',
      avatar: 'https://example.com/images/avatar.jpg'
    }
  },
  {
    id: 3,
    no: '20230817003',
    createTime: new Date('2023-08-17T12:00:00'),
    type: 1,
    terminal: 10,
    userId: 1003,
    userIp: '192.168.1.3',
    userRemark: '',
    status: 10,
    productCount: 1,
    finishTime: new Date('2023-08-18T09:15:00'),
    cancelTime: null,
    cancelType: null,
    remark: '',
    payOrderId: 10003,
    payed: true,
    payTime: new Date('2023-08-17T12:30:00'),
    payChannelCode: 'alipay_app',
    originalPrice: 25,
    orderPrice: 20,
    discountPrice: 5,
    deliveryPrice: 5,
    adjustPrice: 0,
    payPrice: 20,
    deliveryTemplateId: 2001,
    logisticsId: 3002,
    logisticsNo: 'DEF987654',
    deliveryStatus: 2,
    deliveryTime: new Date('2023-08-18T10:30:00'),
    receiveTime: new Date('2023-08-19T11:30:00'),
    receiverName: 'Sarah Johnson',
    receiverMobile: '555-123-4567',
    receiverAreaId: 4003,
    receiverPostCode: 67890,
    receiverDetailAddress: '789 Oak Ave',
    afterSaleStatus: 0,
    refundPrice: 0,
    couponId: 2001,
    couponPrice: 5,
    pointPrice: 0,
    receiverAreaName: 'Villageville',
    items: [
      {
        id: 105,
        userId: 1003,
        orderId: 3,
        spuId: 5005,
        spuName: 'Widget E',
        skuId: 6005,
        picUrl: 'https://example.com/images/widget_e.jpg',
        count: 1,
        originalPrice: 20,
        originalUnitPrice: 20,
        discountPrice: 5,
        payPrice: 15,
        orderPartPrice: 15,
        orderDividePrice: 15,
        afterSaleStatus: 0,
        properties: [
          { propertyId: 7001, propertyName: 'Color', valueId: 8006, valueName: 'Black' },
          { propertyId: 7002, propertyName: 'Size', valueId: 8002, valueName: 'Medium' }
        ]
      }
    ],
    user: {
      id: 1003,
      nickname: 'sarahjohnson',
      avatar: 'https://example.com/images/avatar.jpg'
    }
  }
]
